<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260911184658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chatbot_conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, messages JSON NOT NULL, exports JSON NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_764526E8A76ED395 ON chatbot_conversation (user_id)');
        $this->addSql('CREATE TABLE security_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, attempted_identifier VARCHAR(180) DEFAULT NULL, ip_address VARCHAR(45) NOT NULL, user_agent TEXT DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, http_method VARCHAR(10) DEFAULT NULL, context JSON DEFAULT NULL, resolved BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D712E90DA76ED395 ON security_event (user_id)');
        $this->addSql('CREATE INDEX idx_security_event_ip ON security_event (ip_address)');
        $this->addSql('CREATE INDEX idx_security_event_type ON security_event (type)');
        $this->addSql('CREATE INDEX idx_security_event_severity ON security_event (severity)');
        $this->addSql('CREATE INDEX idx_security_event_created_at ON security_event (created_at)');
        $this->addSql('CREATE TABLE site_alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site VARCHAR(100) NOT NULL, etat VARCHAR(50) NOT NULL, trafic_j DOUBLE PRECISION DEFAULT NULL, capacite_mbps DOUBLE PRECISION DEFAULT NULL, taux_utilisation DOUBLE PRECISION DEFAULT NULL, variation_j1 DOUBLE PRECISION DEFAULT NULL, variation_j7 DOUBLE PRECISION DEFAULT NULL, type_trans VARCHAR(50) DEFAULT NULL, classification VARCHAR(50) DEFAULT NULL, message TEXT NOT NULL, date_alerte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE site_prediction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site VARCHAR(255) NOT NULL, horizon VARCHAR(20) NOT NULL, horizon_heures INT NOT NULL, trafic_actuel_mbps NUMERIC(15, 4) DEFAULT NULL, trafic_projete_mbps NUMERIC(15, 4) DEFAULT NULL, capacite_mbps NUMERIC(15, 4) DEFAULT NULL, taux_utilisation_projete_pct NUMERIC(8, 2) DEFAULT NULL, facteur_croissance NUMERIC(8, 4) DEFAULT NULL, occurrences_projetees INT DEFAULT NULL, etat_predit VARCHAR(40) DEFAULT NULL, action_priorite VARCHAR(20) DEFAULT NULL, action_code VARCHAR(60) DEFAULT NULL, action_description TEXT DEFAULT NULL, projection_fiable BOOLEAN DEFAULT true, date_prediction TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_sp_site ON site_prediction (site)');
        $this->addSql('CREATE INDEX idx_sp_etat ON site_prediction (etat_predit)');
        $this->addSql('CREATE TABLE trafic_historique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site VARCHAR(255) NOT NULL, date_jour DATE DEFAULT NULL, max_trafic NUMERIC(15, 4) DEFAULT NULL, capacite_mbps NUMERIC(15, 4) DEFAULT NULL, max_speed NUMERIC(15, 4) DEFAULT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_importation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_th_site ON trafic_historique (site)');
        $this->addSql('CREATE INDEX idx_th_date_heure ON trafic_historique (date_heure)');
        $this->addSql('CREATE TABLE workflow_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(255) DEFAULT NULL, new_status VARCHAR(255) DEFAULT NULL, action VARCHAR(100) NOT NULL, details TEXT DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, user_email VARCHAR(255) DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25F6E6FB700047D2 ON workflow_history (ticket_id)');
        $this->addSql('ALTER TABLE chatbot_conversation ADD CONSTRAINT FK_764526E8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE security_event ADD CONSTRAINT FK_D712E90DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_history ADD CONSTRAINT FK_25F6E6FB700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE site');
        $this->addSql('ALTER TABLE analyse_resultat ADD s1_fail_duration NUMERIC(15, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE analyse_resultat ADD s1_fail_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD email_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD alert_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA93035F72 FOREIGN KEY (alert_id) REFERENCES site_alert (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_BF5476CA93035F72 ON notification (alert_id)');
        $this->addSql('ALTER TABLE processed_site ADD data_hash VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD s1_fail_duration DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD s1_fail_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD supervision_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD reminder_snoozed_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD capacite_mbps NUMERIC(15, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD observation_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD capacity_reminder_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD capacite_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ADD last_action_performed VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE processed_site ALTER max_trafic_tdd TYPE NUMERIC(15, 2)');
        $this->addSql('ALTER TABLE processed_site ALTER max_trafic_fdd TYPE NUMERIC(15, 2)');
        $this->addSql('ALTER TABLE processed_site ALTER capacite_tdd_mbps TYPE NUMERIC(15, 2)');
        $this->addSql('ALTER TABLE processed_site ALTER capacite_fdd_mbps TYPE NUMERIC(15, 2)');
        $this->addSql('ALTER TABLE ticket ADD current_step INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD total_steps INT DEFAULT 8 NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD processed_sites INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD total_sites INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE ticket ADD sites_progress JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD comments JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD proof_urls JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD notified_levels JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_history DROP max_trafic');
        $this->addSql('ALTER TABLE ticket_history DROP capacite_mbps');
        $this->addSql('ALTER TABLE ticket_history ALTER site DROP NOT NULL');
        $this->addSql('ALTER TABLE ticket_history ALTER date_jour TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE ticket_site ADD status VARCHAR(20) DEFAULT \'pending\' NOT NULL');
        $this->addSql('ALTER TABLE ticket_site ADD current_step_code VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_site ADD current_step_index INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE ticket_site ADD total_steps INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE ticket_task DROP CONSTRAINT fk_60a5ce1d502cb44e');
        $this->addSql('DROP INDEX idx_60a5ce1d502cb44e');
        $this->addSql('ALTER TABLE ticket_task ADD deploiement_data JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_task DROP site_validated');
        $this->addSql('ALTER TABLE ticket_task RENAME COLUMN next_assigned_to_id TO ticket_site_id');
        $this->addSql('ALTER TABLE ticket_task ADD CONSTRAINT FK_60A5CE1DFA714F14 FOREIGN KEY (ticket_site_id) REFERENCES ticket_site (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_60A5CE1DFA714F14 ON ticket_task (ticket_site_id)');
        $this->addSql('ALTER INDEX uniq_user_access_log_user RENAME TO UNIQ_4818F3FCA76ED395');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE site (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, status VARCHAR(50) NOT NULL, service VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE chatbot_conversation DROP CONSTRAINT FK_764526E8A76ED395');
        $this->addSql('ALTER TABLE security_event DROP CONSTRAINT FK_D712E90DA76ED395');
        $this->addSql('ALTER TABLE workflow_history DROP CONSTRAINT FK_25F6E6FB700047D2');
        $this->addSql('DROP TABLE chatbot_conversation');
        $this->addSql('DROP TABLE security_event');
        $this->addSql('DROP TABLE site_alert');
        $this->addSql('DROP TABLE site_prediction');
        $this->addSql('DROP TABLE trafic_historique');
        $this->addSql('DROP TABLE workflow_history');
        $this->addSql('ALTER TABLE analyse_resultat DROP s1_fail_duration');
        $this->addSql('ALTER TABLE analyse_resultat DROP s1_fail_date');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA93035F72');
        $this->addSql('DROP INDEX IDX_BF5476CA93035F72');
        $this->addSql('ALTER TABLE notification DROP email_sent_at');
        $this->addSql('ALTER TABLE notification DROP alert_id');
        $this->addSql('ALTER TABLE processed_site DROP data_hash');
        $this->addSql('ALTER TABLE processed_site DROP s1_fail_duration');
        $this->addSql('ALTER TABLE processed_site DROP s1_fail_date');
        $this->addSql('ALTER TABLE processed_site DROP supervision_until');
        $this->addSql('ALTER TABLE processed_site DROP reminder_snoozed_until');
        $this->addSql('ALTER TABLE processed_site DROP capacite_mbps');
        $this->addSql('ALTER TABLE processed_site DROP observation_until');
        $this->addSql('ALTER TABLE processed_site DROP capacity_reminder_until');
        $this->addSql('ALTER TABLE processed_site DROP capacite_updated_at');
        $this->addSql('ALTER TABLE processed_site DROP last_action_performed');
        $this->addSql('ALTER TABLE processed_site ALTER max_trafic_tdd TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE processed_site ALTER max_trafic_fdd TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE processed_site ALTER capacite_tdd_mbps TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE processed_site ALTER capacite_fdd_mbps TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE ticket DROP current_step');
        $this->addSql('ALTER TABLE ticket DROP total_steps');
        $this->addSql('ALTER TABLE ticket DROP processed_sites');
        $this->addSql('ALTER TABLE ticket DROP total_sites');
        $this->addSql('ALTER TABLE ticket DROP sites_progress');
        $this->addSql('ALTER TABLE ticket DROP comments');
        $this->addSql('ALTER TABLE ticket DROP proof_urls');
        $this->addSql('ALTER TABLE ticket DROP deadline');
        $this->addSql('ALTER TABLE ticket DROP notified_levels');
        $this->addSql('ALTER TABLE ticket_history ADD max_trafic DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_history ADD capacite_mbps DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_history ALTER site SET NOT NULL');
        $this->addSql('ALTER TABLE ticket_history ALTER date_jour TYPE DATE');
        $this->addSql('ALTER TABLE ticket_site DROP status');
        $this->addSql('ALTER TABLE ticket_site DROP current_step_code');
        $this->addSql('ALTER TABLE ticket_site DROP current_step_index');
        $this->addSql('ALTER TABLE ticket_site DROP total_steps');
        $this->addSql('ALTER TABLE ticket_task DROP CONSTRAINT FK_60A5CE1DFA714F14');
        $this->addSql('DROP INDEX IDX_60A5CE1DFA714F14');
        $this->addSql('ALTER TABLE ticket_task ADD site_validated VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_task DROP deploiement_data');
        $this->addSql('ALTER TABLE ticket_task RENAME COLUMN ticket_site_id TO next_assigned_to_id');
        $this->addSql('ALTER TABLE ticket_task ADD CONSTRAINT fk_60a5ce1d502cb44e FOREIGN KEY (next_assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_60a5ce1d502cb44e ON ticket_task (next_assigned_to_id)');
        $this->addSql('ALTER INDEX uniq_4818f3fca76ed395 RENAME TO uniq_user_access_log_user');
    }
}
